# Generated by Django 4.2.3 on 2023-07-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='Course', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_username', models.CharField(default='username', max_length=200)),
                ('student_email', models.EmailField(default='email', max_length=200)),
                ('student_password', models.CharField(default='pass', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTakesCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.student')),
            ],
        ),
    ]
