# Generated by Django 4.2.3 on 2023-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_delete_studenttakescourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='first_app.student'),
        ),
    ]
