# Generated by Django 4.2.3 on 2023-07-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_professor_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.student')),
            ],
        ),
    ]
